# Generated by Django 4.2.1 on 2023-05-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsList',
            fields=[
                ('items_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('food', 'food'), ('sports', 'sports')], max_length=20)),
                ('subcategory', models.CharField(choices=[('vegetables', 'vegetables'), ('fruit', 'fruit'), ('cricket', 'cricket'), ('football', 'football')], max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
